-libraryjars /home/mypapit/wtk251/lib/mmapi.jar:/home/mypapit/wtk251/lib/midpapi20.jar:/home/mypapit/wtk251/lib/wma11.jar:/home/mypapit/wtk251/lib/cldcapi11.jar
-injars /home/mypapit/wtk251/apps/MobiMoon/bin/MobiMoon.jar
-outjar /tmp/MobiMoon.jar
-keep public class * extends javax.microedition.midlet.MIDlet 
